### PR TITLE
Minor changes for docs

### PR DESCRIPTION
**Pull request by skirpichev**
- added autodoc_default_options sphinx directive
- added nitpicky sphinx directive (test for broken references)
- amended c10ebcb (gmpy2._context -> gmpy2.context)
- sphinx's default_role used to add cross-references to gmpy2/python objects/functions/classes
- more simple function signature for round2()
- exceptions added to the sphinx docs (no docstrings yet)

### CODE REVIEW

**Comment by casevh** [comment]
It looks like I did something wrong. Can you help me get it fixed?

**Comment by skirpichev** [comment]
Sure, I'll take a look today.

**Comment by skirpichev** [comment]
@casevh, these conflicts are (at least most of them) due to merging you pr #388 (which in turn reverts my pr https://github.com/aleaxit/gmpy/pull/386).

I would guess it was a mistake.  In this case, @casevh, please merge first #393 (a copy of reverted pr), then this pr (if conflicts disappear).

**Comment by skirpichev** [comment]
Ok, @casevh, now conflicts are solved.

**Comment by casevh** [comment]
Thanks again for all the assistance.

Case

**Pull request merged**
