### PR TITLE
Fix cython C-API imports.

### PR DESCRIPTION
**Pull request by pkittenis**
Correct fix for #189. Replaces #190

### CODE REVIEW

**Comment by vinklein** [comment]
Don't work for me :

```
vklein@azure:~/Installer/gmpy$ git pull pkittenis cython_api_import_fix 
From https://github.com/pkittenis/gmpy
 * branch            cython_api_import_fix -> FETCH_HEAD
Already up-to-date.
vklein@azure:~/Installer/gmpy$ pip install . --user
Processing /home/vklein/Installer/gmpy
Building wheels for collected packages: gmpy2
  Running setup.py bdist_wheel for gmpy2 ... done
  Stored in directory: /tmp/pip-ephem-wheel-cache-kgqlcw/wheels/13/77/5c/05c08d4016cd7f339bf3c6ef3ad6dfa3ad3613d373fd01000d
Successfully built gmpy2
Installing collected packages: gmpy2
  Found existing installation: gmpy2 2.1.0a3.dev0
    Uninstalling gmpy2-2.1.0a3.dev0:
      Successfully uninstalled gmpy2-2.1.0a3.dev0
Successfully installed gmpy2-2.1.0a3.dev0
vklein@azure:~/Installer/gmpy$ python test_cython/
runtests.py      setup_cython.py  
vklein@azure:~/Installer/gmpy$ python test_cython/runtests.py 
()
Unit tests for gmpy2 2.1.0a3dev0 with Cython 0.28.2
()
Compiling test_cython.pyx because it changed.
[1/1] Cythonizing test_cython.pyx
running build_ext
building 'test_cython' extension
creating build
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/home/vklein/.local/lib/python2.7/site-packages/gmpy2 -I/tmp/tmpFD_Z5Z -I/usr/lib/python2.7 -I/usr/lib/python2.7/plat-x86_64-linux-gnu -I/usr/lib/python2.7/lib-tk -I/usr/lib/python2.7/lib-old -I/usr/lib/python2.7/lib-dynload -I/home/vklein/.local/lib/python2.7/site-packages -I/usr/local/lib/python2.7/dist-packages -I/usr/lib/python2.7/dist-packages -I/usr/lib/python2.7/dist-packages/gtk-2.0 -I/usr/include/python2.7 -c test_cython.c -o build/temp.linux-x86_64-2.7/test_cython.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -Wl,-Bsymbolic-functions -Wl,-z,relro -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/test_cython.o -lgmp -lmpfr -lmpc -o /tmp/tmpFD_Z5Z/test_cython.so
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "test_cython.pyx", line 5, in init test_cython
    import_gmpy2()
AttributeError: 'module' object has no attribute '_C_API'
cython test failed
vklein@azure:~/Installer/gmpy$ python
Python 2.7.12 (default, Nov 20 2017, 18:23:56) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import gmpy2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "gmpy2/__init__.py", line 1, in <module>
    from .gmpy2 import *
ImportError: No module named gmpy2
>>> 
```

**Comment by pkittenis** [comment]
You are running python from the source directory which has a `gmpy2` package. That overrides the installed `gmpy2`. The source dir does not have the extension built. So import fails.

Either cd out of the source dir, or run `setup.py build_ext -i`. The other error is being discussed in #190

**Comment by vinklein** [comment]
> You are running python from the source directory which has a gmpy2 package. That overrides the installed gmpy2. The source dir does not have the extension built. So import fails.

Yes indeed, my bad.

**Comment by pkittenis** [comment]
From #190 :

> casevh: I'm fine with adding explicit imports for _C_API and the _mpmath* helper functions.

Cool, added the three used internal variables and functions, see diff. `test_cython/runtests.py` is now passing:

```
python test_cython/runtests.py 
()
Unit tests for gmpy2 2.1.0a3dev0 with Cython 0.28.2
()
Compiling test_cython.pyx because it changed.
[1/1] Cythonizing test_cython.pyx
running build_ext
building 'test_cython' extension
creating build
creating build/temp.linux-x86_64-2.7
x86_64-linux-gnu-gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -I/home/panos/gmpy/env/local/lib/python2.7/site-packages/gmpy2-2.1.0a3.dev0-py2.7-linux-x86_64.egg/gmpy2 -I/tmp/tmpTRSpcI -I/home/panos/gmpy/env/lib/python2.7 -I/home/panos/gmpy/env/lib/python2.7/plat-x86_64-linux-gnu -I/home/panos/gmpy/env/lib/python2.7/lib-tk -I/home/panos/gmpy/env/lib/python2.7/lib-old -I/home/panos/gmpy/env/lib/python2.7/lib-dynload -I/usr/lib/python2.7 -I/usr/lib/python2.7/plat-x86_64-linux-gnu -I/usr/lib/python2.7/lib-tk -I/home/panos/gmpy/env/local/lib/python2.7/site-packages -I/home/panos/gmpy/env/local/lib/python2.7/site-packages/gmpy2-2.1.0a3.dev0-py2.7-linux-x86_64.egg -I/home/panos/gmpy/env/lib/python2.7/site-packages -I/home/panos/gmpy/env/lib/python2.7/site-packages/gmpy2-2.1.0a3.dev0-py2.7-linux-x86_64.egg -I/usr/include/python2.7 -c test_cython.c -o build/temp.linux-x86_64-2.7/test_cython.o
x86_64-linux-gnu-gcc -pthread -shared -Wl,-O1 -Wl,-Bsymbolic-functions -Wl,-Bsymbolic-functions -Wl,-z,relro -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -D_FORTIFY_SOURCE=2 -g -fstack-protector --param=ssp-buffer-size=4 -Wformat -Werror=format-security build/temp.linux-x86_64-2.7/test_cython.o -lgmp -lmpfr -lmpc -o /tmp/tmpTRSpcI/test_cython.so
test_check... pass
test_mpc... pass
test_mpc_cmp... pass
test_mpc_from_mpc... pass
test_mpc_from_mpfr... pass
test_mpfr... pass
test_mpfr_cmp... pass
test_mpfr_from_mpfr... pass
test_mpq... pass
test_mpq_cmp... pass
test_mpq_from_mpq... pass
test_mpq_from_mpz... pass
test_mpz... pass
test_mpz_cmp... pass
test_mpz_from_mpz... pass
test_py_check... pass
All tests pass!
```

**Comment by casevh** [comment]
Thank you for all the help in the new build process.

**Pull request merged**
