### PR TITLE
Use PyLong_GetSign()

### PR DESCRIPTION
**Pull request by skirpichev**
See https://github.com/python/cpython/pull/116561 and https://github.com/capi-workgroup/decisions/issues/19.  I'm not happy with this API and it seems that discussion is ongoing.  Maybe it's wise to wait some time...

### CODE REVIEW

**Comment by skirpichev** [comment]
Probably, discussion in https://github.com/capi-workgroup/decisions/issues/19 is ended.

**Comment by casevh** [comment]
Should this be merged now and then released as 2.2.0 or should this wait until 2.2.1?

**Comment by skirpichev** [comment]
> Should this be merged now and then released as 2.2.0

I don't think so.  https://github.com/capi-workgroup/decisions/issues/29 is open.  We should wait, see also https://discuss.python.org/t/c-api-working-group-vacancy-again/56167

This pr shouldn't block 2.2 release.  I'll just mark it as a draft.

**Comment by skirpichev** [comment]
I don't like it, but probably https://github.com/capi-workgroup/decisions/issues/35 API will have ``negative`` field.  So, probably we can skip this.

**Pull request closed without merging**
