### PR TITLE
Misc fixes

### PR DESCRIPTION
**Pull request by skirpichev**
~~2e96fb6 Avoid computing _PyHASH_MODULUS in GMPy_MPQ_Hash_Slot()~~
~~324e284 Fix compiler warning~~
8a7b1ff Fix rst markup in docstrings (for emphasis)
12afc77 Use ``gmpy2.__package__`` to get project name in sphinx
b470a3b Set doctest_global_cleanup sphinx directive

### CODE REVIEW

**Review by casevh — COMMENTED** [review]
I need to test the _PyHASH_MODULUS change on 64-bit Windows. mpz_set_si() accepts a long (32-bit) but _PyHASH_MODULUS is too large. At least that's my first reaction. I will respond later with the test results.

**Comment by skirpichev** [comment]
On Sat, Nov 04, 2023 at 02:13:46PM -0700, casevh wrote:
>    I need to test this on 64-bit Windows. mpz_set_si() accepts a long
>    (32-bit) but _PyHASH_MODULUS is too large. At least that's my first
>    reaction. I will respond later with the test results.

Yep, we should use mpz_set_ui().

**Review by casevh — COMMENTED** [review]
It's worse than that. 64-bit Windows defines `long` as a 32-bit integer and `long long` as a 64-bit integer. Most other 64-bit platforms define both `long` and `long long` as 64-bit integers. GMP expects `si` and `ui` to be `long` and they don't offer functions that accept `long long`.

Here is the compile error message with the last change:
\gmpy\src\gmpy2_hash.c(67): warning C4305: 'function': truncation from 'unsigned __int64' to 'unsigned long'

One of the quirks that makes supporting Windows difficult.

Let's just skip the _PyHASH change for now. I found a few other conversion warnings that I need to resolve first.

**Comment by skirpichev** [comment]
Ok, first comment was removed.  It seems we really want ``_PyHASH_BITS`` macro.

**Comment by skirpichev** [comment]
Change in ``_mpfr_hash()`` was reverted too, @casevh

**Comment by casevh** [comment]
Thanks for your patience in dealing with these subtle issues.

**Comment by skirpichev** [comment]
Hash-related patch was moved to #453

**Pull request merged**
