### PR TITLE
declare macro for MPQ in gmpy2.h

### PR DESCRIPTION
**Pull request by vinklein**
linked to #121

### CODE REVIEW

**Comment by casevh** [comment]
I'm currently refactoring gmpy2.h to reduce the number of header files that need to be installed. I've added the MPQ macro to my work in progress. I'll comment again when I've pushed my changes.

**Comment by casevh** [comment]
I've pushed an updated gmpy2.h that includes the MPQ macro. I modified setup.py to only install gmpy2.h. You may need to manually delete the unneeded headers that have already been install. If you ware working in an existing build environment, you will need to run "python setup.py clean" to delete the old build directories.

**Comment by vinklein** [comment]
The compilation work with python3
With python2 I got the following errors :

> ```
> In file included from src/gmpy2.c:412:0:
> src/gmpy2.h:106:5: error: unknown type name ‘Py_hash_t’
>      Py_hash_t hash_cache;
>      ^
> src/gmpy2.h:117:5: error: unknown type name ‘Py_hash_t’
>      Py_hash_t  hash_cache;
>      ^
> src/gmpy2.h:123:5: error: unknown type name ‘Py_hash_t’
>      Py_hash_t hash_cache;
>      ^
> src/gmpy2.h:130:5: error: unknown type name ‘Py_hash_t’
>      Py_hash_t hash_cache;
> ```
it's solved by moving 

> #if PY_VERSION_HEX < 0x030200A4
> typedef long Py_hash_t;
> typedef unsigned long Py_uhash_t;
> #  define _PyHASH_IMAG 1000003
> #endif
before line 106

**Comment by casevh** [comment]
Fixed. Thanks for patches.

**Comment by vinklein** [comment]
It works perfectly, thanks

**Pull request closed without merging**
