### PR TITLE
Support parsing of CPython-style numeric literals

### PR DESCRIPTION
**Pull request by skirpichev**
I'm less certain about the second commit (56afdc1).  There is no a direct analog of mpfr() in the CPython stdlib.  Thus, perhaps we shouldn't support here CPython-style parsing...

### CODE REVIEW

**Comment by casevh** [comment]
The fallback to int() when mpz() fails is okay, except slower, since it does not lose precision. I don't want the loss of precision by converting to a float first.

I looked at the code in _Py_string_to_number_with_underscores. I think the logic can be converted to support mpz/mpq/mpfr/mpc conversions. For mpz(), I would change the logic for "underscores only allowed after decimal digits" to either rely on the specified base or just allow digits and all upper/lower case ASCII characters. I'll give it a try tonight or tomorrow.

**Comment by skirpichev** [comment]
> I don't want the loss of precision by converting to a float first.

Well, maybe we should use less strict approach.  In fact, the Decimal class of stdlib - does violate the PEP 515 (https://bugs.python.org/issue44267) and this is ok...  So, probably we can just strip underscores in case of mpfr.

As I told you before, maybe all this stuff belongs to gmp/mpfr.  Other projects implement similar workarounds for string format restrictions of mpz/mpq/etc.  For example, https://github.com/ocaml/Zarith/pull/75.  What do you think?

**Comment by skirpichev** [comment]
Ok, the second commit was replaced with a more simple solution, mentioned before.

**Comment by casevh** [comment]
I'm working on an updated change based on the approach you used for mpfr. I'm just removing all underscore characters. It it working but ...

Unrelated, I'm tracking down some reference leaks.

**Comment by skirpichev** [comment]
> I'm just removing all underscore characters.

That's a bad approach in general (PEP violation).  For mpfr() it might be fine due to mentioned above reason.  But not for int's.

**Comment by skirpichev** [comment]
Ok, @casevh, apparently this pr is not relevant anymore.  I still think, however, that for mpz() your solution with replace() is wrong (violation of the PEP 515).  But feel free to close related issue #210, if you disagree.

**Pull request closed without merging**
