### PR TITLE
Use pyproject.toml for metadata and drop support for old CPython versions

### PR DESCRIPTION
**Pull request by skirpichev**

### CODE REVIEW

**Comment by casevh** [comment]
I will commit this after I release v3.1.3. I'll update the version to 3.2 at that time also.

**Comment by skirpichev** [comment]
@casevh, maybe you can do a minor release with wheels for the 3.11?

**Comment by casevh** [comment]
I think I did something wrong with the pull request. There was a conflict with setup.py that I tried to fix. I'm not certain what I did wrong. Git still confuses me at times. All the test builds broke.

I will just merge it and assume I just need to fix setup.py.

If I need help, I'll add a comment.

**Comment by casevh** [comment]
Fixed setup.py and local build is working. Updated version to 2.2.0a1 and pushed.

Thank you for this change.

Case

**Pull request merged**
