### PR TITLE
Run Cython tests for binary wheels

### LINKED ISSUE #447: cython C-API is broken in published wheels (and in the build_wheels.yml CI workflow)
The problem is that we bundle libraries.

Then, first, probably we should also supply relevant header files (gmp.h, etc).  Next, document how user can specify a custom path (gmpy2.libs) to libraries in the setup.py.

### PR DESCRIPTION
**Pull request by skirpichev**
Closes #447

### CODE REVIEW

**Comment by skirpichev** [comment]
This is an incomplete version so far: MacOS wheels aren't tested yet.  Also, probably we should document how users can use bundled libraries for their extensions.

**Comment by casevh** [comment]
Am I inadvertently blocking progress on this PR?

**Comment by skirpichev** [comment]
> Am I inadvertently blocking progress on this PR?

No, that's entirely my fault.  Some further progress is in [test-wheels-cython2](https://github.com/skirpichev/gmpy/tree/test-wheels-cython2) branch.

I'll try to finish this pr today, sorry for a delay.

**Comment by skirpichev** [comment]
Ok, now it works on MacOS too.

**Comment by casevh** [comment]
Looks fine. I'll merge the PR and then test with my Windows build process.

**Comment by skirpichev** [comment]
Hmm, this was a draft.  This I think that related issue isn't solved: at least this pr lacks documentation.

**Pull request merged**
