### PR TITLE
Revert "Correct function/methods signatures + minor fixes"

### PR DESCRIPTION
**Pull request by casevh**
Reverts aleaxit/gmpy#386

### CODE REVIEW

**Comment by skirpichev** [comment]
Hmm, why you did this?

**Comment by casevh** [comment]
I'm tired tonight. Just confused. Sorry.

**Comment by skirpichev** [comment]
Ok, I thought you have some objections against #386 and it was mistakenly merged.  Lets I'll fix merge conflicts next time;)

**Comment by casevh** [comment]
Thanks.

Case

**Comment by skirpichev** [comment]
@casevh, why this was merged?
Do you have some objections against the https://github.com/aleaxit/gmpy/pull/386, which this pr reverts?

**Pull request merged**
