### PR TITLE
Simplify wheels building (linux and macos)

### PR DESCRIPTION
**Pull request by skirpichev**
* now arm64 MacOS builds are in the build_wheels
* wheels are tested with test/runtests.py (not for arm64 on MacOS!)

### CODE REVIEW

**Comment by casevh** [comment]
I like the improvements to the build process and the testing.

I would like to continue building GMP, MPFR, and MPC from source. Partly for control of the build options (i.e. some MPFR optimizations are possible when it can depend on GMP internals) and to allow testing of different combinations of library versions. And partly to be able to provide the full source code used to build the libraries included in the wheels.

**Comment by skirpichev** [comment]
@casevh, now building of GMP, MPFR and MPC from sources - restored on the MacOS with few changes:
* ad7fa45b6695fab7c11c3b2b2d21894b795db4ae was reverted (see comments)
* custom CPP/LDFLAGS removed for arm64 builds (I'm not sure if this is still required: if so, it would be nice to add some comments.)

@bebound, as an author of #321, could you please test arm64 wheels?  Now this stuff goes to the build_wheels.yml workflow.  Unfortunately, added testing of wheels is unavailable for the MacOS on arm64.

**Comment by bebound** [comment]
The arm64 build is not working.
The file size (184k) is much smaller than previous one (664k).
```
>>> import gmpy2
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/homebrew/lib/python3.10/site-packages/gmpy2/__init__.py", line 1, in <module>
    from .gmpy2 import *
ImportError: dlopen(/opt/homebrew/lib/python3.10/site-packages/gmpy2/gmpy2.cpython-310-darwin.so, 0x0002): symbol not found in flat namespace '___gmp_bits_per_limb'
```

**Comment by casevh** [comment]
Thanks.

Case

**Comment by skirpichev** [comment]
@casevh, I'm sorry, but this patch break things for arm64 builds (see [this comment](https://github.com/aleaxit/gmpy/pull/361#issuecomment-1407544866) @bebound ).  I didn't expect you merge this pr before I fix this.

**Comment by casevh** [comment]
My apologies. I was a bit to aggressive. I'll take a quick look at it. too.

Case

**Comment by skirpichev** [comment]
> I was a bit to aggressive.

I think so.  Unfortunately, as I mentioned before - arm64 wheels are not tested (despite of green status on the Github Actions CI).

I'll prepare a fix today or tomorrow.  (Or a reversion for this pr.)

**Comment by casevh** [comment]
I think you may need to separate "auto" and "arm64" builds. Here is one error I spotted in pip_install_gmpy2 

ld: warning: ignoring file /usr/local/lib/libmpfr.dylib, building for macOS-arm64 but attempting to link with file built for macOS-x86_64

It's late for me.

Case

**Pull request merged**
