### PR TITLE
Enable coverage testing in CI

### PR DESCRIPTION
**Pull request by skirpichev**
* genhtml output stored in the build artifact
* few new coverage tests (seems to be correct, but please check)
* upload coverage results to the codecov.io (that, probably, needs some configuration on your side)

### CODE REVIEW

**Comment by skirpichev** [comment]
That's now c-code coverage may look: https://app.codecov.io/github/codecov/example-c

**Comment by casevh** [comment]
This looks great. Thanks for all the help.

The integration with Codecov (and readthedocs.io) highlights an issue/challenge. I'm not the owner of this repository. The actual owner is Alex Martelli. I took over maintenance from him. I'll try to contact him to see if he can make the required changes.

gmpy2 will eventually need a new home. I just don't know when to make the change and where it should land.

I plan to commit this as-is in a few days. If the attempts to use Codecov generate spam, I'll remove that integration until I can do it properly. (If your comment "and the bot can be disabled." relates to this, please let me know.)

Case

**Comment by skirpichev** [comment]
> The integration with Codecov (and readthedocs.io) highlights an issue/challenge.

Yes.  You can take look to the build log (with lcov output) and download the genhtml output from build artifact, but...

> gmpy2 will eventually need a new home. I just don't know when to make the change and where it should land.

Maybe just your fork could be a new home?

> If the attempts to use Codecov generate spam

I meant above comment of [codecov-commenter](https://github.com/codecov-commenter).

IIRC, this can be turned off either via their web interface or with `.codecov.yml` in the repo (with `comment: false`).

**Comment by casevh** [comment]
Thanks.

Case

**Comment by skirpichev** [comment]
That's how code coverage on codecov.io looks like for the gmpy2:
https://app.codecov.io/gh/skirpichev/gmpy

**Comment by skirpichev** [comment]
Hmm, now coverage data is available on https://app.codecov.io/gh/aleaxit/gmpy, but the coverage status for project/patch isn't shown with other pr status checks.

**Pull request merged**
