### PR TITLE
Remove calls of obsolete mpfr functions

### PR DESCRIPTION
**Pull request by skirpichev**

### CODE REVIEW

**Comment by skirpichev** [comment]
Failure: Ubuntu 16.04 doesn't have MPFR >= 4.  Let me know if it does make sense to support this release.

**Comment by skirpichev** [comment]
Ok, I've added "#if" block.

**Comment by skirpichev** [comment]
@casevh, does this make sense for you?

**Comment by casevh** [comment]
The functions you've changed are already guarded by a version check and they are only used with MPFR v3.x. There is a lot of duplicated code but that's a different issue.

Is there a scenario where compilation fails on an old Linux distribution?

I'll test on Ubuntu 16.04 again but it was fine the last time I checked.

**Comment by skirpichev** [comment]
> The functions you've changed are already guarded by a version check and they are only used with MPFR v3.x.

@casevh, yes.  But the #192 was about removing warnings from these checks.

The only problem I see is a different sign conventions for mpfr_root() and mpfr_rootn_ui().

> Is there a scenario where compilation fails on an old Linux distribution?

I doubt.  For old MPFR we fallback on the old code.

**Comment by skirpichev** [comment]
Ok, I think this should be closed.

**Pull request closed without merging**
